### ISSUE TITLE
Could we get an example of how to read Heroku config vars?

### ISSUE THREAD

**Issue by juanjgarcia** [weibeld/heroku-buildpack-run#10]
The documentation mentions `ENV_DIR` as a source for the Heroku environment. How does one use this?

It would make the package far more useful if all the Heroku environment variables were available in the runtime environment. This does not seem to be the case?

Thanks

**Comment by juanjgarcia** [comment]
I have found an example here:
https://devcenter.heroku.com/articles/buildpack-api#bin-compile

**Comment by juanjgarcia** [comment]
https://github.com/weibeld/heroku-buildpack-run/pull/11

**Comment by weibeld** [comment]
I added a feature allowing to load the config vars as env vars, see [README](https://github.com/weibeld/heroku-buildpack-run#loading-config-variables). It's similar to your implementation in #11 with some measures to prevent variable name clashes.

**Comment by juanjgarcia** [comment]
Cool! Nice work @weibeld! Thanks
