### ISSUE TITLE
Custom script name

### ISSUE THREAD

**Issue by aymericbouzy** [weibeld/heroku-buildpack-run#4]
Would it be possible to configure the script name? For instance `compile-assets.sh` instead of `buildpack-run.sh`, which doesn't mean anything to me.
Not exactly sure how to configure this though: env variable?

**Comment by weibeld** [comment]
The issue has been addressed. Now you can set the filename with `heroku config:set BUILDPACK_RUN=my_file.sh`. It's also possible to specify multiple files by separating them with colons.

**Comment by aymericbouzy** [comment]
Perfect! Did you implement that right away when I suggested it? I'm impressed! I think the issue can be closed.

**Comment by weibeld** [comment]
I implemented it the next day, yes ;) I hope that the buildpack is helpful to you.

**Comment by aymericbouzy** [comment]
Yes it is! I have a React-Rails stack, I use it to compile my webpack project before providing it to rails assets.

**Comment by weibeld** [comment]
That's great! Feel free to recommend the buildpack to anybody if it was useful to you :)
