### ISSUE TITLE
Stop the build if a script fails

### ISSUE THREAD

**Issue by vsemionov** [weibeld/heroku-buildpack-run#8]
Hi,

Thank you very much for this useful tool!

My issue is that the buildpack doesn't abort the build if a script exits with a non-zero code. For example, a script could be downloading a vital file for your application. If it fails to download it, the script would exit with a non-zero exit code. The buildpack should stop the build to prevent deploying a partially built application. I believe this may be achieved simply by adding `set -e` at the beginning of `/bin/compile`, but I haven't verified this.

This is a duplicate of #2, but the issue was closed by the submitter, without any explanation.

Best regards,
Victor

**Comment by weibeld** [comment]
Hi there,

I just added it. There are also some other changes. You can now specify any types of commands in addition to shell scripts, e.g. binaries and native UNIX commands.

For most users this shouldn't change anything, except that now any shell scripts must be executable, i.e. they must have a `#!/bin/bash` line and the executable flag set (`chmod +x script.sh`).

Let me know if the changes work for you.

**Comment by justinkchen** [comment]
The weird thing is that this actually broke deploys for us just now.

``` 
-----> Running: ./buildpack-run.sh
/app/tmp/buildpacks/d4963cfdc610c1afed0921a93443e079284fcd2706707c8a33c3d1220c492dbfcb751a745f252dfc67a3828cf1f3cdd01d6bf5d0fc25fa0b511b62c391305643/bin/compile: line 61: ./buildpack-run.sh: Permission denied
-----> Aborting build because './buildpack-run.sh' exited with a non-zero code (126)
 !     Push rejected, failed to compile Run app.
 !     Push failed
```

We have a script that generates a static.json file and saves it, but for some reason, the latest changes caused a permission denied issue which then quit the whole deploy. I works fine on the last commit before all of your recent changes though.

**Comment by justinkchen** [comment]
oh just read your message above, seems like i need to add: `#!/bin/bash` line and set the flag

**Comment by weibeld** [comment]
Yes, shell scripts are now executed rather than sourced. Thus:

1. `#!/bin/bash`
2. `chmod +x buildscipt-run.sh`

**Comment by bigboateng** [comment]
> Yes, shell scripts are now executed rather than sourced. Thus:
> 
> 1. `#!/bin/bash`
> 2. `chmod +x buildscipt-run.sh`

@weibeld where do you run the command `chmod +x buildscipt-run.sh`? locally?

**Comment by weibeld** [comment]
@bigboateng Yes locally, then commit and push as usual.

**Comment by vsemionov** [comment]
@weibeld Perfect, it works now! Thank you very much!

**Comment by weibeld** [comment]
@vsemionov Great, you're welcome!
